frr version 8.4
frr defaults datacenter
hostname LEAF-2
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip ospf area 0
!
interface eth0
 ip ospf network point-to-point
 ip ospf area 0
 mpls ldp sync
!
interface swp1
 ip ospf network point-to-point
 ip ospf area 0
 mpls ldp sync
!
router ospf
 ospf router-id 10.255.255.22
 passive-interface default
 no passive-interface eth0
 no passive-interface swp1
 network 10.255.255.22/32 area 0
 network 10.0.0.4/31 area 0
 network 10.0.0.6/31 area 0
!
mpls ldp
 router-id 10.255.255.22
 address-family ipv4
  discovery transport-address 10.255.255.22
  interface eth0
  interface swp1
 exit-address-family
!
router bgp 65000
 bgp router-id 10.255.255.22
 no bgp default ipv4-unicast
 neighbor SPINES peer-group
 neighbor SPINES remote-as 65000
 neighbor SPINES update-source lo
 neighbor SPINES send-community
 neighbor SPINES send-community extended
 neighbor 10.255.255.11 peer-group SPINES
 neighbor 10.255.255.12 peer-group SPINES
 !
 address-family l2vpn evpn
  neighbor SPINES activate
  advertise-all-vni
 exit-address-family
!
end
