frr version 8
service integrated-vtysh-config
hostname LEAF2
!
router ospf
 ospf router-id 10.255.0.2
 passive-interface default
 no passive-interface swp1
 no passive-interface swp2
 network 10.255.0.2/32 area 0.0.0.0
 network 10.254.0.2/32 area 0.0.0.0
 network 10.254.12.12/32 area 0.0.0.0
!
router bgp 65000
 bgp router-id 10.255.0.2
 neighbor RR peer-group
 neighbor RR remote-as 65000
 neighbor RR update-source lo
 neighbor 10.255.255.11 peer-group RR
 neighbor 10.255.255.12 peer-group RR
 !
 address-family ipv4 unicast
  network 10.255.0.2/32
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor RR activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
!
router bgp 65000 vrf AI_FABRIC
 bgp router-id 10.255.0.2
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  route-target import 50110:50110
  route-target export 50110:50110
 exit-address-family
!
router bgp 65000 vrf AI_SERVICES
 bgp router-id 10.255.0.2
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  route-target import 50130:50130
  route-target export 50130:50130
 exit-address-family
!
router bgp 65000 vrf TENANT_B
 bgp router-id 10.255.0.2
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  route-target import 50210:50210
  route-target export 50210:50210
 exit-address-family
!
line vty
