frr version 8
service integrated-vtysh-config
hostname LEAF4
!
router ospf
 ospf router-id 10.255.0.4
 passive-interface default
 no passive-interface swp1
 no passive-interface swp2
 network 10.255.0.4/32 area 0.0.0.0
 network 10.254.0.4/32 area 0.0.0.0
 network 10.254.34.34/32 area 0.0.0.0
!
router bgp 65000
 bgp router-id 10.255.0.4
 neighbor RR peer-group
 neighbor RR remote-as 65000
 neighbor 10.255.255.11 peer-group RR
 neighbor 10.255.255.12 peer-group RR
 !
 address-family l2vpn evpn
  neighbor RR activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
!
line vty
